GRANT ALTER,INSERT,UPDATE,DELETE,SELECT,EXECUTE ON *.* TO 'lmrlm'@'localhost' IDENTIFIED BY 'lmrlm@tiantong' WITH GRANT OPTION;
GRANT ALTER,INSERT,UPDATE,DELETE,SELECT,EXECUTE ON *.* TO 'lmrlm'@'%' IDENTIFIED BY 'lmrlm@tiantong' WITH GRANT OPTION;
GRANT SELECT ON *.* TO 'guest'@'%' IDENTIFIED BY 'guest@tiantong' WITH GRANT OPTION;