/*==============================================================*/
/* SET group_concat_max_len=102400;
/*==============================================================*/

/*==============================================================*/
/* codes below generated by PowerDesigner                                                  */
/*==============================================================*/

drop table if exists player;

/*==============================================================*/
/* Table: player                                                */
/*==============================================================*/
create table player
(
   id                   int not null auto_increment,
   MAC                  char(100) not null,
   gem                  int(10) default 0,
   password             char(100) not null,
   playername           char(40) not null,
   roomId               int(10) default 0,
   createTime           bigint,
   primary key (id),
   unique key INDEX_PLAYER_USER_ID (MAC),
   unique key INDEX_PLAYER_PLAYERNAME (playername)
)
ENGINE = InnoDB
auto_increment = 10000
default character set = utf8;

/*==============================================================*/
/* PROCEDURE & FUNCTION                                           */
/*==============================================================*/
delimiter $$
DROP PROCEDURE if exists `onUserLogon`$$
CREATE PROCEDURE `onUserLogon` (IN playerId BIGINT, IN now BIGINT)
BEGIN
    DECLARE lastLogonTime, curDate BIGINT;
    DECLARE curDailyLogonCount INT(10);
    SET curDate = UNIX_TIMESTAMP(CURDATE()) * 1000;
    SELECT logonTime, dailyLogonCount INTO lastLogonTime, curDailyLogonCount FROM player WHERE id = playerId;
    IF lastLogonTime IS NOT NULL THEN
        IF lastLogonTime < curDate THEN
            SET curDailyLogonCount = 0;
        END IF;
    END IF;
	UPDATE player SET isOnline = 1, logonTime = now, dailyLogonCount = curDailyLogonCount + 1 WHERE id = playerId;
END$$
