/*==============================================================*/
/* SET group_concat_max_len=102400;
/*==============================================================*/

/*==============================================================*/
/* codes below generated by PowerDesigner                                                  */
/*==============================================================*/

drop table if exists player;

/*==============================================================*/
/* Table: player                                                */
/*==============================================================*/
create table player
(
   id                   int not null auto_increment,
   MAC                  char(100) not null,
   gem                  int(10) default 0,
   password             char(100) not null,
   playername           char(40) not null,
   roomId               int(10) default 0,
   createTime           bigint,
   primary key (id),
   unique key INDEX_PLAYER_USER_ID (MAC),
   unique key INDEX_PLAYER_PLAYERNAME (playername)
)
ENGINE = InnoDB
auto_increment = 10000
default character set = utf8;

