/*==============================================================*/
/* SET group_concat_max_len=102400;
/*==============================================================*/

/*==============================================================*/
/* codes below generated by PowerDesigner                                                  */
/*==============================================================*/

drop table if exists GMAccount;

/*==============================================================*/
/* Table: GMAccount                                             */
/*==============================================================*/
create table GMAccount
(
   id                   bigint(20) not null auto_increment,
   username             char(64),
   password             char(40),
   privilege            char(10),
   primary key (id),
   unique key AK_Key_username (username)
)
auto_increment = 10000
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;